### ISSUE TITLE
Qiskit-Ignis tutorial for expectation value measurement mitigation

### ISSUE THREAD

**Issue by HuangJunye** [qiskit-community/qiskit-advocate-mentorship-program#10]
# Description
Recently, a new measurement error mitigation technique was added in [Qiskit Ignis](https://github.com/Qiskit/qiskit-ignis). 
In this project, we will create a tutorial about this new feature which is based on [this paper](https://arxiv.org/abs/2006.14044).
 
# Mentor/s
Hwajung Kang (@HwajungKang), Quantum community and education developer at IBM Quantum.

# Type of participant
Someone who knows basics of stochastic processes and linear algebra. 

# Number of participants
1

# Deliverable
Create Qiskit tutorial for expectation value measurement mitigation

**Comment by HwajungKang** [comment]
replaced by #40
