### ISSUE TITLE
Implement the meta-VQE algorithm

### ISSUE THREAD

**Issue by Cryoris** [qiskit-community/qiskit-advocate-mentorship-program#14]
# Description
The variational quantum eigensolver (VQE) is maybe one of the famous quantum algorithms: provided with a Hamiltonian describing a quantum system and a parameterized ansatz state, it finds the optimal parameters such that the ansatz minimizes the energy of the system. In chemistry, finding the ground state is a hard problem and the VQE is a promising candidate to solve systems we're unable to solve classically.

The meta-VQE is a generalization of the VQE, where you not only have a parameterized ansatz but can also have a parameterized Hamiltonian. The details are discussed in this paper: https://arxiv.org/pdf/2009.13545.pdf. 

The goal of this project is to implement the meta-VQE algorithm in Qiskit.

# Mentor/s
Julien Gacon (@Cryoris), Pre-Doc researcher at IBM Research Zurich, Qiskit Terra and Aqua core developer 

# Type of participant
You know the basics of Qiskit and the VQE, and ideally have worked with the VQE in the past. You don't have to be a chemist for this (neither am I)!

# Number of participants
1 (possibly 2)

# Deliverable
A PR with the meta-VQE to Qiskit.

**Comment by eraraya-ricardo** [comment]
I am interested in this project and I noticed that the author of the paper has made a Jupyter Notebook tutorial but in PennyLane (https://github.com/AlbaCL/qhack21/blob/main/Meta-VQE.ipynb). I am putting the link here since I think it will be useful for this project.
