### ISSUE TITLE
Generalizing Grover Adaptive Search for optimization with constraints

### ISSUE THREAD

**Issue by Cryoris** [qiskit-community/qiskit-advocate-mentorship-program#17]
# Description
Grover Adaptive Search (Ref. [1]) is an optimization algorithm based on Grover search. The idea behind the algorithm is to define "hits in the database" as all states that produce an objective value beneath a certain threshold. By iteratively decreasing the threshold until only state is left we can find the minimum. Qiskit implement this algorithm in `qiskit.optimization.algorithms.GroverOptimizer` to solve quadratic unconstrained binary problems (QUBOs). (see tutorials [2])

In the current format we cannot add constraints to the optimization problem. We can, however, generalize the algorithm to also take constraints into account by:
* adding an additional auxiliary qubit encode the information on whether a constraint is met or not and 
* requiring that these auxilary qubits are `True` (or in state 1) to be a database hit

[1]: https://arxiv.org/abs/1912.04088
[2]: https://qiskit.org/documentation/tutorials/optimization/4_grover_optimizer.html

# Mentor/s
Julien Gacon (@Cryoris), Pre-Doc researcher at IBM Research Zurich, Qiskit Terra and Aqua core developer

# Type of participant
You should have basic knowledge of Qiskit and Python, and ideally (but not necessarily required) are familiar with Grover's algorithm and mathematical optimization -- or even know the Grover Adaptive Search paper! 

# Number of participants
1

# Deliverable
A PR to Qiskit generalizing the `GroverOptimizer`, maybe also extending the existing tutorial.

**Comment by hykavitha** [comment]
Please add me to this work.

**Comment by HuangJunye** [comment]
@hykavitha Thanks for the interest in this project. I can see that you have indicated this project as your 1st choice in the application from. Now you are all set! Of course, you are welcome to ask Julien any questions about the project in this issue.

**Comment by dotslaser** [comment]
@Cryoris  @HuangJunye Hi! Has there been any progress on this issue? I can't find any documentation related to this. Thanks!!
