### ISSUE TITLE
Implement/integrate t|ket> routing in Qiskit

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-community/qiskit-advocate-mentorship-program#25]
# Description
Qiskit loses against t|ket> in the [QUEKO benchmarks](https://arxiv.org/abs/2002.09783) ([video](https://www.youtube.com/watch?v=Z9R9a3hku9Y)). One option is to integrate t|ket> routing elements into Qiskit, but I'm not sure if their license is fully compatible with ours. Ideally, we could reimplement the algorithm from [their paper](https://drops.dagstuhl.de/opus/volltexte/2019/10397/pdf/LIPIcs-TQC-2019-5.pdf). In any case, I think it might be fun.

# Mentor/s
@1ucian0 

# Type of participant
Python coder and paper reader.

# Number of participants
1 (2 if they have good coordination)

# Deliverable
PR with Qiskit transpiler pass(es)

**Comment by mtreinish** [comment]
tket is proprietary software and not compatible for use within qiskit at all. Also pytket already extends qiskit: https://github.com/CQCL/pytket if you are willing to agree to their licensing terms.

**Comment by 1ucian0** [comment]
While it might be possible to extract some good ideas from [their paper](https://arxiv.org/pdf/1902.08091.pdf) I'm not sure if the level of details is good enough and about the legal implications in terms of IP.
