### ISSUE TITLE
Applied Quantum Machine Learning for Image Classification

### ISSUE THREAD

**Issue by amacaluso** [qiskit-community/qiskit-advocate-mentorship-program#35]
# Description
In the last few years, many Quantum Machine Learning (QML) algorithms have been proposed in the literature, promising several theoretical advantages with respect to their classical counterparts. However, when it comes to actual implementation to solve typical data analysis problems, there are many technical issues to face.

In this project, the idea is to write one or more tutorials to train and test a custom Quantum ML model in a typical Data Science scenario for an image classification problem. The purpose is twofold: first, help practitioners in Machine Learning (ML) to approach a typical classification problem where a quantum-classical variational algorithm is employed as an ML model. On the other hand, to provide a guide to people in the Quantum Computing (QC) community to test variational algorithms on a specific, custom dataset. 

# Mentor/s
<Are you able to mentor this project?>

# Type of participant
People with a background in Statistics or Machine Learning

# Number of participants
1-2

# Deliverable
One or more technical blog about QML and/or a chapter of the qiskit textbook

**Comment by kareem1925** [comment]
I would love to help and participate
